## GLOBAL
#
#Logging
log_file: app.log
#Integration IP - 0.0.0.0 if global.
source_host: 0.0.0.0
#Integration path where Bastille webhooks will be sent.
source_path: /zone-detections
#Integration port where Bastille webhooks will be sent.
source_port: 8001
# Algo screen will clear if no alerts are triggered for this amount of time.
clear_time: 60
# ONLY monitored protocols will alert.
monitored_protocols:
  - cellular
  - wifi
  - ble
# If device tagged with below tags, will NOT alert.
allowed_tags:
  - authorized
  - exclude
#
## FREEPORT
#
#vendor: Freeport 
#target_host: 10.35.44.51 
#target_port: 80
#auth_username: bn
#auth_password: bn
#
# ALGO
#
vendor: Algo
target_host: http://172.30.2.119
target_port: 80
auth_username: admin
auth_password: algo
text_color: red
strobe_pattern: 2
strobe_color: red
#    "tonelist":
#        "bell-na.wav",
#        "bell-uk.wav",
#        "buzzer.wav",
#        "chime.wav",
#        "dogs.wav",
#        "gong.wav",
#        "page-notif.wav",
#        "speech-test.wav",
#        "tone-1kHz-max.wav",
#        "warble1-low.wav",
#        "warble2-med.wav",
#        "warble3-high.wav",
#        "warble4-trill.wav"
# Set tone on/off and recording from above default list (or record your own)
tone: True
tone_wav: bell-na.wav
