#Vendor - Algo or Freeport
vendor: Freeport
#Logging
log_file: app.log
#Integration IP - 0.0.0.0 if global.
source_host: 0.0.0.0
#Integration path.
source_path: /zone-detections
#Integration port.
source_port: 8000
#Algo screen IP or host.
#target_host: http://172.30.2.118
#Freeport IP
target_host: 172.30.2.240
#Algo or Freeport API port.
target_port: 2311
#Algo screen username.
#auth_username: admin
# Algo screen password.
#auth_password: algo
#Freeport screen username.
auth_username: bn
# Freeport screen password.
auth_password: bn
# Algo screen will clear if no alerts are triggered for this amount of time.
clear_time: 300
# ONLY monitored protocols will alert.
monitored_protocols: 
  - cellular
  - wifi
  - ble
# If device tagged with below tags, will NOT alert.
allowed_tags:
  - authorized
  - exclude
# Strobe variables. Pick pattern and color. 
strobe_pattern: 2
strobe_color: amber
#    "tonelist":
#        "bell-na.wav",
#        "bell-uk.wav",
#        "buzzer.wav",
#        "chime.wav",
#        "dogs.wav",
#        "gong.wav",
#        "page-notif.wav",
#        "speech-test.wav",
#        "tone-1kHz-max.wav",
#        "warble1-low.wav",
#        "warble2-med.wav",
#        "warble3-high.wav",
#        "warble4-trill.wav"
# Set tone on/off and recording from above default list (or record your own)
tone: True
tone_wav: joe_voice.wav