#Logging
log_file: app.log
#Integration IP - 0.0.0.0 if global.
source_host: 0.0.0.0
#Integration path.
source_path: /zone-detections
#Integration port.
source_port: 8000
#Algo screen IP or host.
target_host: http://172.30.2.118
#Algo screen username.
auth_username: admin
# Algo screen password.
auth_password: algo
# Algo screen will clear if no alerts are triggered for this amount of time.
clear_time: 100
# ONLY monitored protocols will alert.
monitored_protocols: 
  - cellular
  - wifi
  - ble
# If device tagged with below tags, will NOT alert.
allowed_tags:
  - authorized
  - exclude
# Strobe variables. Pick pattern and color. 
strobe_pattern: 2
strobe_color: amber

